# Generated by Django 3.2.8 on 2021-11-19 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='publicaciones/')),
                ('titulo', models.CharField(max_length=100,
                 verbose_name='Título de la publicación')),
                ('fecha_publicacion', models.DateField(
                    auto_now_add=True, verbose_name='Fecha de Publicacion')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('estatus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                 to='catalogos.estatus', verbose_name='Estatus')),
            ],
        ),
    ]
