# Generated by Django 3.2.8 on 2021-12-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='publicaciones/')),
                ('titulo', models.CharField(max_length=100,
                 verbose_name='Título de la publicación')),
                ('fecha_publicacion', models.DateField(
                    auto_now_add=True, verbose_name='Fecha de Publicacion')),
            ],
        ),
    ]
