# Generated by Django 3.2.8 on 2021-12-05 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='usuarios.usuario', verbose_name='Usuario Postulante'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='estatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='catalogos.estatus', verbose_name='Estatus'),
        ),
    ]
