# Generated by Django 3.2.8 on 2021-12-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='revisiones/'),
        ),
    ]
